//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bloomberglp.BlpapiExamples.UnitTests.MktNotifier.MktNotifierTests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServiceSchema {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceSchema() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bloomberglp.BlpapiExamples.UnitTests.MktNotifier.MktNotifierTests.Resources.Servi" +
                            "ceSchema", typeof(ServiceSchema).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;ServiceDefinition name=&quot;blp.apiauth&quot; version=&quot;1.0.7.2&quot;&gt;
        ///    &lt;service name=&quot;//blp/apiauth&quot; version=&quot;1.0.7.2&quot;&gt;
        ///        &lt;operation name=&quot;AuthorizationRequest&quot; serviceId=&quot;99&quot;&gt;
        ///            &lt;request&gt;Request&lt;/request&gt;
        ///            &lt;requestSelection&gt;AuthorizationRequest&lt;/requestSelection&gt;
        ///            &lt;response&gt;Response&lt;/response&gt;
        ///            &lt;responseSelection&gt;AuthorizationSuccess&lt;/responseSelection&gt;
        ///            &lt;responseSelection&gt;AuthorizationFailure&lt;/responseSelecti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string apiauthSchema {
            get {
                return ResourceManager.GetString("apiauthSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;ServiceDefinition name=&quot;blp.mktdata&quot; version=&quot;1.0.1.0&quot;&gt;
        ///   &lt;service name=&quot;//blp/mktdata&quot; version=&quot;1.0.0.0&quot; authorizationService=&quot;//blp/apiauth&quot;&gt;
        ///      &lt;event name=&quot;MarketDataEvents&quot; eventType=&quot;MarketDataUpdate&quot;&gt;
        ///         &lt;eventId&gt;0&lt;/eventId&gt;
        ///         &lt;eventId&gt;1&lt;/eventId&gt;
        ///         &lt;eventId&gt;2&lt;/eventId&gt;
        ///         &lt;eventId&gt;3&lt;/eventId&gt;
        ///         &lt;eventId&gt;4&lt;/eventId&gt;
        ///         &lt;eventId&gt;9999&lt;/eventId&gt;
        ///      &lt;/event&gt;
        ///      &lt;defaultServiceId&gt;134217729&lt;/defaultServiceI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mktdataSchema {
            get {
                return ResourceManager.GetString("mktdataSchema", resourceCulture);
            }
        }
    }
}
